# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eRegistry' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.2.0'
  pod 'MBProgressHUD', '~> 1.0.0'

  # Pods for eRegistry

  target 'eRegistryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eRegistryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
